spring:
  config:
    activate:
      on-profile: local

  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 8081