spring:
  config:
    activate:
      on-profile: docker

  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379

  cloud:
    gateway:
      routes:
        - id: member-service-authentication-required
          uri: lb://member-service
          predicates:
            - Path=/members/logout
          filters:
            - name: AuthenticationFilter

        - id: member-service-authentication-non-required
          uri: lb://member-service
          predicates:
            - Path=/members/**

        - id: cart-item-service-authentication-required
          uri: lb://cart-item-service
          predicates:
            - Path=/cart-items/**
          filters:
            - name: AuthenticationFilter

        - id: product-service-authentication-non-required
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service-authentication-non-required
          uri: lb://order-service
          predicates:
            - Path=/orders/internal/**

        - id: order-service-authentication-required
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: AuthenticationFilter

        - id: payment-service-authentication-required
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8081/eureka

jwt:
  secret:
    c3ByaW5nLWJvb3QtY2FzaGZsb3ctcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=