spring:
  config:
    activate:
      on-profile: docker

  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://product-service-db:3306/flash-sales-market
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8081/eureka/