server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flash-sales-market
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

resilience4j:
  retry:
    instances:
      default:
        base-config: default
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 500

  circuitbreaker:
    instances:
      default:
        base-config: default
    configs:
      default:
        # sliding window
        sliding-window-type: count_based
        sliding-window-size: 5

        #failure call
        failure-rate-threshold: 60

        # slow call
        slow-call-rate-threshold: 80
        slow-call-duration-threshold:
          seconds: 3

        minimum-number-of-calls: 5

        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        wait-duration-in-open-state:
          seconds: 10
