spring:
  config:
    activate:
      on-profile: test

  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    enabled: false

server:
  port: 8084

kafka:
  host: localhost
  port: 9094